### ISSUE TITLE
An actual use-example

### ISSUE THREAD

**Issue by IngwiePhoenix** [TimeToogo/Pinq#21]
Hey.

I am working with Yii's 1.1.x version and I would like to extend `CActiveRecord` to implement Pinq. 

So I looked into the documentation but all I find is either a very long class list, or examples where the original classes with their implementation is not shown - or at least a pseudo implementation. There also seems to be no detail how Pinq is actually used by the developer.

I am aware of this one: http://elliotswebsite.com/Pinq/api.html
...but it is just a method listing and an explanation of what is for what, but i can't make up an implementation from this.

Could you maybe give a short example for a possible implementation? Thanks!

Kind regards, Ingwie

**Comment by TimeToogo** [comment]
Looking for code examples of using this library?

There is the [examples page on the project site](http://elliotswebsite.com/Pinq/examples.html).

**Comment by IngwiePhoenix** [comment]
I saw that, but the description of the project sounded like you'd rather implement it's interfaces

```php
<?php class MyData extends ... implements ITraversable {
    // Implement functions, like for a Database?
}
$data = new MyData("table_name");
$res = $data->where(...)->take(...);
```

Or did I missunderstand the way of implementing?

**Comment by TimeToogo** [comment]
This library provides a collection API with an out of the box implementation based on iterators to allow you to use it with arrays such as with the examples I linked to. It also provides a way to implement this API with other data sources as you seem to be attempting (eg a database), 

I think the main problem is that you are underestimating the amount of work to implement it as you describe, it is not nearly as simple as implementing an interface. Although this library covers much of the groundwork, you would ultimately have to map PHP expression trees to the language of your desired back-end (the db). If you want have look at how this can be done there is a relevant repo [Pinq.Demo.Sql](https://github.com/TimeToogo/Pinq.Demo.Sql). This contains a basic implementation of mapping the PINQ API to a MySQL back-end as well as extensive documentation describing the process and high level structure.

**Comment by IngwiePhoenix** [comment]
Yes - I am well aware. I browsed the source tree and had a look into the actual documentation briefly - I was at school. But I have a rough idea of how large PINQ is - don't worry about that. :)

The demo repo will help a lot, ill go and read the code in a little. Thanks for pointing it out!

Nevertheless, I see Pinq as the most complete LINQ implementation, and i want to be able to use this with some actual usecase within my app. :)

Kind regards, Ingwie

**Comment by TimeToogo** [comment]
Fantastic! Wish you luck on your venture.

**Comment by IngwiePhoenix** [comment]
So a few months later I returned to PINQ. I did post my code on Github now and am aiming to make my app into Beta pretty soon. but I am still being very icky about some of Yii's default ideas - using `CDataProvider` and `CActiveMethod` still feels limited. So I re-visited the Pinq.Demo.Sql repo and tried to make out what I would have to do.

...untill I realized that this demo actually created a query and ran it on the backend. What I was looking for was to write a class that wrapped aroud `CDbCriteria`, which basically builds the SQL as well by passing PHP options. But getting the options correct in an intuitive way is ...

```php
# https://github.com/DragonsInn/BIRD3/blob/master/protected/modules/user/controllers/UserController.php#L101
    public function actionList($page=1,$q=false) {
        $this->pageTitle = "Show all users";
        $perPage = 50;
        $limitBegin = $perPage*($page-1);
        // Determine if we should respond to an AJAX call.
        if($q == false || $q == null) {
            // Calculate the numbers
            $count = User::model()->count();
            $pages = ceil($count/$perPage);
            $remainder = $count % $perPage;
            $dbc = new CDbCriteria();
            $dbc->limit = $perPage;
            $dbc->offset = $limitBegin;
            $users = User::model()->findAll($dbc);
            if($pages < $page-1) {
                // Reset to page 1
                return $this->redirect(["/user/list"]);
            }
        } else {
            // We are queried to search for a user.
            $adp = new CActiveDataProvider("User", [
                "criteria"=>[
                    "condition"=>"username LIKE :q OR email LIKE :q",
                    "params"=>[":q"=>$q],
                    "limit"=>$perPage,
                    "offset"=>$limitBegin
                ]
            ]);
            $users = $adp->getData();
            $pages = ceil(count($users)/$perPage);
            if($pages < $page-1) {
                return $this->redirect(["/user/list", "q"=>$q]);
            }
        }
        $this->render("list", [
            "users"=>$users,
            "pages"=>$pages,
            "page"=>$page
        ]);
    }
```

... not funny. That is why I wanted to make a clean implementation using PINQ.

I noticed that `ITraversable` wraps only a tiny amount of functins. `IRepository` is mentioned int he demo, but I was unable to find an explanation of the "most important" interfaces.

Can you explain the interfaces that I would have to comply to? o.o

**Comment by TimeToogo** [comment]
It is a complicated task. I highly recommend reading through [Pinq.Demo.Sql documentation](https://github.com/TimeToogo/Pinq.Demo.Sql#documentation) even though this does not completely match your use case, it is very similar. The repo contains a bunch of README.md files which explain the process of implementing a query provider so hopefully this will be of use.
