### ISSUE TITLE
Only variable references should be returned by reference

### ISSUE THREAD

**Issue by sidneywidmer** [TimeToogo/Pinq#23]
I get en error in `IteratorGenerator`, method `&getIterator`: Only variable references should be returned by reference. This should fix the problem. The error first occurred when I updated my server from php 5.6.7 to 5.6.8...

```
$generator = $this->iteratorGenerator($this->iterator);
return $generator;
```

I'm not really sure what exactly is the problem here and if this is a good fix. Otherwise I could create a pullrequest.

**Comment by TimeToogo** [comment]
This should be fixed in 3.2.0
